- default.json
This is an internal types package that is equivalent to a DefinitelyTyped package.
> auto merge @seek/ie-shared-types

- default.json
This should create separate PRs from the rest of the dev dependencies, which is helpful to isolate e.g. linting changes.
> Include skuba in blessed list of SEEK packages

- .github/CODEOWNERS
- CONTRIBUTING.md
- README.md
> Add CONTRIBUTING.md

- default.json
This is a workaround until Renovate fixes their branch/PR limits.
> Open PRs immediately after branch creation

- .github/workflows/validate.yml
- default.json
- package.json
- yarn.lock
> Run config validation in CI

- default.json
`pino@7` has been released and we're moving over to it:
https://github.com/seek-oss/logger/pull/17
> Undo `pino-pretty` block

- README.md
This isn't particularly obvious.
> Document ignoring a specific version

- default.json
- non-critical.json
- third-party-major.json
This release was an unintended breaking change.
dwyl/aws-sdk-mock#256
> Block aws-sdk-mock 5.5.0

- default.json
- non-critical.json
- third-party-major.json
> Block faker@6.6.6

- default.json
- non-critical.json
- third-party-major.json
> Block `@types/faker` renovation

- .github/workflows/validate.yml
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
- https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
> Lock down GitHub workflow

- .github/workflows/validate.yml
- Lock down permissions
- Pin action versions
- Remove unnecessary LFS support
> Uplift workflows

- .github/workflows/validate.yml
- default.json
- non-critical.json
- package.json
- yarn.lock
At the moment when you trigger a renovate manually it can get stuck in a "Pending" state. This annoys me alot because it means I have to wait for the Renovate Dashboard to list something as "Pending" and then click again.
There's a fix detailed here: https://github.com/renovatebot/renovate/discussions/21720#discussioncomment-5711470
To set branch creation immediate and internal filter to strict.
> Fix Renovate Config

- default.json
- non-critical.json
- third-party-major.json
Context for SEEKers: https://seekchat.slack.com/archives/CDCPCEPV3/p1695191657208039
> Disable major upgrades over launch period

- README.md
- default.json
- non-critical.json
- third-party-major.json
This has the same memory leak as 4.21.0 (#102).
> Block dd-trace@3.42.0

- default.json
- non-critical.json
- third-party-major.json
Allow major upgrades after launch.
Context for SEEKers: https://seekchat.slack.com/archives/CA18J5J0L/p1706479113253499
> Revert - Disable major upgrades over launch period #96

- default.json
- non-critical.json
- third-party-major.json
Most teams are currently not ready for serverless 4's licensing changes.
> Disable serverless 4

- default.json
- non-critical.json
- third-party-major.json
I'm seeing build-rebase loops, and suspect it's related to this given an old/suspiciously similar issue: https://github.com/renovatebot/renovate/issues/21004
> Temporarily remove gitIgnoredAuthors

- default.json
- third-party-major.json
- https://github.com/seek-oss/rynovate/pull/124
- [matchUpdateTypes](https://docs.renovatebot.com/configuration-options/#matchupdatetypes)
> Auto merge docker pinDigest updates

- default.json
- non-critical.json
- third-party-major.json
After migration tweaks:
https://github.com/seek-oss/rynovate/pull/111
> Migrate to matchDepName

- default.json
- non-critical.json
- third-party-major.json
https://github.com/seek-oss/skuba/pull/1577/files#diff-b6e3ec0b6754640bf0e4fa5da12435bbfc919627cc1f1e92500fa2ac5d0f3436R20-R21
Working here:
https://github.com/samchungy/renovate-experiments/pull/28
> Introduce DataDog Lambda Layer custom manager

- default.json
- non-critical.json
- third-party-major.json
We're ready now: https://github.com/seek-oss/rynovate/pull/113
> Allow serverless V4

- default.json
Tested: https://github.com/samchungy/renovate-experiments
> Allow node 22 bump

- default.json
https://github.com/SEEK-Jobs/indie-metrics-api/pull/668
Seems to work: https://github.com/samchungy/renovate-experiments/pull/46/files
> Enable renovate on datadog extensions in deeper infra folders

- default.json
- non-critical.json
- third-party-major.json
There are some disruptive error handling changes that I'd like to see whether or not end up settled or not before upgrading
> Block gaxios majors

- default.json
- internal-shared.json
- non-critical.json
- third-party-major.json
> Share common settings in their own file

- default.json
- internal-shared.json
Not sure about `seek-koala` but in particular for the Koa 3 upgrades I gotta update all 3.
> Group koa packages

- internal-shared.json
https://github.com/koajs/router/issues/202 is a pretty critical bug
> Block @koa/router 14

- default.json
Build green = good to go on these I think
> Automerge pnpm minor and patches

- default.json
- internal-shared.json
- non-critical.json
- third-party-major.json
> Restore Nx renovation & lock file maintenance

- default.json
Align with https://github.com/seek-oss/skuba/pull/2065.
> Clean up `minimumReleaseAge`

- default.json
Attempting to make skuba add the `CI=true` variable to Dockerfiles before peoples pipelines start breaking
ie avoiding https://github.com/SEEK-Jobs/indie-dua-lipa/pull/1801
> RFC: Group skuba v12.14.1 with pnpm v10.17.x

- default.json
https://github.com/zbrydon/test-renovate/pull/10
> Group serverless updates
