- README.md
- default.json
The golang.org modules (golang.org/x/foo) are essentially always updated. With the current configuration of Mon/Fri updates an no grouping it's like a game of whack-a-mole to get `seek-auth-sidecar`'s PRs merged.
This treats digest updates like `aws-sdk` and only updates digests on the first of the month with grouping.
> Group gomod digest updates

- README.md
- non-critical.json
Gantry releases need to be synchronised across a Gantry environment. It's really annoying to have the non-critical packages at a different cadence to the critical ones. Right now I need to manually open PRs for the non-criticals at the same time Renovate opens the critical ones.
I'm not sure how kosher it is to refer to SEEK internal projects from SEEK-OSS. Gantry isn't particularly secret and there's been talk of open sourcing it anyway, however.
> Match Gantry schedule for non-critical

- default.json
Theoretically these PRs should have no impact on what's installed to `node_modules`. It's easy to forget a pin so it'd be good to clear out these PRs automatically.
> Automerge pin updates

- default.json
This should match the version of Node the project uses. Right now we're tracking `@types/node@14` which isn't LTS yet.
> fix(types/node): Disable major @types/node upgrade

- default.json
Candidate Data Contracts defines the types on candidate domain, and it is hard to keep it up to date with all PRs raised by renovate.
Assuming it will be merged only if the buildkite pipeline passes, it would be nice to add it as auto merge same away as the other types library, if possible.
> Add candidate data contracts to be auto merged

- default.json
Given we want immediate PRs, this needs to be >= the concurrent limit.
> Bump hourly PR limit too

- README.md
- default.json
This breaks up our renovation across two broad timeslots:
- 12am to 3am for automergable dependencies
- 3am to 6am for manually triaged dependencies
The idea is to reduce build agent contention, particularly in the case of automergable dependencies. If these are automatically merged before other PRs are raised, we can eliminate concurrent builds that are made redundant once Renovate rebases on top of the automerged PR.
We can go further in spacing out our schedules; this is just a start that still sticks the high-level schedule documented in the README.
> Segment scheduled times

- default.json
These are released in lockstep so are arguably more noisy than v2.
> Schedule AWS SDK v3 packages monthly

- README.md
- default.json
- third-party-major.json
As discussed on Slack, this alleviates busywork in tracking down vulnerabilities in transitive dependencies.
> Enable lock file maintenance for prod presets

- README.md
- default.json
- third-party-major.json
Landing #25 required a small battle with `@breejs/later` to get it to recognise a fortnightly schedule. It seems the minutes are the key to getting the text parser to work here.
This opens up the door for us to bump a few other things to a fortnightly schedule, but I'll leave that to another PR.
> Spell out `h:mm` in schedules

- non-critical.json
This also shuffles some options around so the defaults are more reasonable, with specific overrides in `packageRules`.
> Align non-critical to 6am cutoff

- default.json
- non-critical.json
- third-party-major.json
Renovate has revised the names of "matcher" properties in package rules to delineate what is rule scope and what is rule configuration.
https://docs.renovatebot.com/configuration-options/#packagerules
> Migrate package rules to matcher style

- default.json
- third-party-major.json
Per Renovate's doco:
> Renovate will evaluate all `packageRules` and not stop once it gets a
> first match. Therefore, you should order your `packageRules` in order
> of importance so that later rules can override settings from earlier
> rules if necessary.
https://docs.renovatebot.com/configuration-options/#packagerules
> Move catch-all rules to the start

- default.json
This is a proper production recommendation now. See https://github.com/seek-oss/braid-design-system/blob/master/docs/treat%20to%20vanilla-extract%20migration.md.
> default: Treat vanilla-extract as first party

- non-critical.json
`@types/node@16` is currently causing some pain.
> non-critical: Disable `@types/node` majors

- non-critical.json
Rynovate's new favourite activity is to upgrade all our non-critical repos to Node 16. Our other presets extend `docker:disableMajor` but it's missing here for some reason.
> Disable Docker major upgrades on non-critical

- default.json
This is causing issues because AWS SDK V3 users typically have `@aws-sdk/types` in their dev dependencies and other `@aws-sdk` packages in their dependencies. Renovate is bumping the former by itself which leads to broken builds.
Instead, just have all aws-sdk packages on a monthly schedule.
> Exclude aws-sdk from dev dependency run

- default.json
Without this, we're getting weird combined PRs like so:
```
deps: lock file maintenance aws-sdk
```
> Unconfuse aws-sdk group and lockfile maintenance

- default.json
- non-critical.json
- third-party-major.json
I've observed behaviour where automerging halts once we've gone past the schedule. My theory is that the `schedule` property is acting as a matcher, and hopefully this means that we can allow automerging outside of the schedule by listing it as a separate package rule.
> Try to force automerging outside of schedule

- default.json
pino-pretty@7 requires pino@7, which has not been released on its stable channel yet.
> Disable pino-pretty@7 renovation

- default.json
This is predominantly used as a types package.
> default: Automerge `@seek/backoffice-access`

- default.json
Help prevent malicious npm package updates - add default stabilityday delay of 3 for non aws-sdk/seek internal packages.
Have tested this config for ~3 weeks in candiman's cm-search-api.
[Option info](https://docs.renovatebot.com/configuration-options/#stabilitydays)
* Added "dependency dashboard" issue. As mentioned in the docs, without this, it is impossible to see future PRs that are delayed due to stabilityDays. It's also a useful way of manually triggering PR creation.
* When updateNotScheduled  is set to true (default previously) - PRs could be updated out of schedule. This caused the noisy dev deps group to be constantly updated, resetting the stabilityDays. Only enable updatenotscheduled for dependency groups with stabilitydays 0
Pics:
> add StabilityDays 3

- non-critical.json
- third-party-major.json
These seem generally useful and don't seem to present any notification spam once you unsubscribe from the issues.
> Enable Dependency Dashboard on other presets

- default.json
This isn't handled by the Apollo GraphQL nor monorepo group presets.
https://docs.renovatebot.com/presets-group/#groupallapollographql
> Group auxiliary Apollo Server packages

- default.json
This was missed in #54 and has led to us missing Gantry PRs.
> default: Expedite SEEK Buildkite plugins

- default.json
#62 was overwritten by the catch-all rule with `"prPriority": 98`, which I forgot covered more than just npm dependencies.
This means that Gantry PRs should have been raised during the typical 3am–6am window. The only other thing that #54 changes was the default `prCreation` setting, and I wonder if that's broken or rate limited in some way such that Renovate never gets around to creating the PR within the window.
> default: Tweak Gantry rule

- default.json
I've decided to extend this beyond the typical 3–6am window since Gantry PRs are often ones you need to action all at once, and wouldn't want to get rate limited behind other PRs.
> default: Reduce Gantry schedule

- default.json
This defaults to `prConcurrentLimit`, however the `stabilityDays` configuration added in #54 can leave pending branches around which eat into this limit. With an added buffer we can ensure that Renovate still creates new branches for other updates that may be ready to be PRed.
> default: Increase `branchConcurrentLimit`

- default.json
This shouldn't be necessary when we have `prConcurrentLimit` and just adds another condition where Renovate may choose to skip work on a particular run.
> default: Remove `prHourlyLimit`

- default.json
We seem to be receiving far fewer Renovate PRs as a result of #54. This includes SEEK deps where I've had to manually go to Dependency Dashboards to force their creation.
My working theory is that a deferred `prCreation` means that Renovate has to take additional passes at a given branch to get it PRed, and that may be leading to some internal rate limiting. Immediate PR creation means that the work can be bundled alongside the initial commit and branch creation.
This doesn't help matters where we need to enforce `stabilityDays`, but may restore some reliability for trusted deps.
> Try to force `prCreation` for trusted deps

- default.json
I'm observing some frontend repos are not getting SEEK dependency upgrades because they are blocked behind pending branches. Unfortunately `branchConcurrentLimit` is a repository-level option so we can't customise its behaviour based on package rules.
> Bump `branchConcurrentLimit` again :(

- default.json
Serverless updates and Serverless plugins have the potential to completely change the runtime behaviour of our Lambdas so we should not bundle them together with other dev dependency updates which "typically" do not affect the runtime
> Exclude Serverless packages from dev deps group

- default.json
Branches can be used as identifiers for things like preview environments.
This can mean that the branch name appears in URLs, either as subdomains, paths or query parameters.
- `cool-feature.example.com`
- `example.com/cool-feature`
- `example.com/path?version=cool-feature`
In these cases it's nice to have URLs with limited special characters.
**Current**
Currently renovate branches have `/` added which results in URLs like:
- `renovate%2Fcool-feature.example.com`
- `example.com/renovate%2Fcool-feature`
- `example.com/path?version=renovate%2Fcool-feature`
**With Change**
With this change it'll instead use `--`:
- `renovate--cool-feature.example.com`
- `example.com/renovate--cool-feature`
- `example.com/path?version=renovate--cool-feature`
**Change**
Default for Branch Prefix is …
> Replace "/" from Renovate Branch Prefix with "--" to be URL Safe

- default.json
`renovate--` appears to be normalised to `renovate-` by Renovate now. This formalises the change so we aren't beholden to Renovate's implementation details which could flip back to respecting `renovate--` in future.
Also see seek-oss/renovate-config-seek#19
> Formalise branch prefix as `renovate-`

- default.json
There are too many Renovate PRs and it is getting hard and hard to keep merging it. Currently we have around 255 renovate PRs opened for profile and apply repositories.
Moving this repos to a an auto-merge for minor and patches changes, it will help profile and apply services to keep the number of PRs opened smaller.
> move profile packages to different package rules

- default.json
- third-party-major.json
Per renovatebot/renovate#19800, the "auto" strategy now raises additional PRs to update dependencies in range. This is either unsuitable for our use case or bugged, as we have "lockfile update" PRs (as denoted by a `-lockfile` branch suffix) which are bumping the in-range version of a package's production dependencies. This means that e.g. `^2.0.0` gets bumped to `^2.1.0` and so on, and results in a lot of transitive noise for projects that consume the package.
I've also patched in widening of peer dependency ranges which is what "auto" was previously described as doing.
https://docs.renovatebot.com/configuration-options/#rangestrategy
https://docs.renovatebot.com/release-notes-for-major-versions/#version-35
https://github.com/renovatebot/renovate/discussions/20990
> Revert range strategy to "replace"

- default.json
- non-critical.json
- third-party-major.json
Package groups should automatically infer `recreateWhen`:
https://docs.renovatebot.com/configuration-options/#recreatewhen
> Remove explicit `recreateClosed`s

- default.json
The aws-sdk moved some deps to the @smithy/ scope.
eg. @aws-sdk/smithy-client is now @smithy/smithy-client
https://github.com/aws/aws-sdk-js-v3/pull/4873
> Add @smithy to aws-sdk group

- default.json
aws-sdk-client-mock-jest and aws-sdk-client-mock are separate packages published in a monorepo. Will be more convenient to update them together
> Add aws-sdk client mock group

- default.json
- non-critical.json
- third-party-major.json
This may smooth over lockfile maintenance without having transitive dependencies introduce duplication of e.g. AWS SDK or TypeScript type packages.
https://github.com/scinos/yarn-deduplicate#deduplication-strategies
> RFC: Use `yarn-deduplicate --strategy fewer`

- default.json
- non-critical.json
- third-party-major.json
These can be removed once we revert #96.
https://nvd.nist.goiv/vuln/detail/CVE-2023-49803
> Permit major upgrades to @koa/cors

- default.json
- non-critical.json
- third-party-major.json
These can be removed once we revert #96.
https://github.com/SEEK-Jobs/ie-logging/releases/tag/v9.0.0
> Permit major upgrades to @seek/ie-logging

- default.json
- non-critical.json
- third-party-major.json
We can revert once DataDog/dd-trace-js#3887 is fixed.
> Disable renovation on dd-trace >= 4.21

- default.json
`eslint-config-seek` now supports ESLint v8:
https://github.com/seek-oss/eslint-config-seek/blob/f09a8ce60b4d33371f1b51c50f8e9b4ac2681e2e/package.json#L46
> Revert #49

- default.json
- non-critical.json
- third-party-major.json
We have lower confidence in new versions of this package; also see #99.
@samchungy notes that this also delays us upgrading from a bad version to a fixed one.
> RFC: Wait longer before renovating `dd-trace`

- default.json
- non-critical.json
- third-party-major.json
This reverts commit 5ab1d2eacd88c6ed99cb082af7b82551544fbefe (#99).
https://github.com/DataDog/dd-trace-js/issues/3887#issuecomment-1867378054
> Re-enable renovation on dd-trace > 4.21

- default.json
- non-critical.json
- third-party-major.json
This is tied to our AWS SDK upgrade: SEEK-Jobs/indie-api-types#911
> Allow `@seek/indie-api-types` major through

- default.json
These should generally be semantic commits as they allow consumers to install later peer dependencies without warnings. I'm not sure why we/I thought to group these beforehand.
I'm keeping the schedule aligned with dev dependencies as it's common to have a package specified under `devDependencies` and `peerDependencies`. Ideally these would even be grouped together but that's a challenge for another day.
> default: Try to fix peer dependency upgrades

- default.json
- non-critical.json
- third-party-major.json
The intent here is to allow Renovate to rebase a branch even if it has a skuba autofix commits that have been pushed. I think this is as simple as hardcoding the fixed bot accounts that we use for this purpose.
seek-oss/skuba#1493
> Ignore autofix commits for SEEK-Jobs and seek-oss

- default.json
- non-critical.json
Excluding node-fetch from major renovate upgrade as it's requires on ESM at the moment and causes some troubles on other renovate PRs
> Exclude node fetch renovate major upgrade

- README.md
- default.json
- non-critical.json
- third-party-major.json
Will fix this warning
Repository problems
These problems occurred while renovating this repository. [View logs](https://developer.mend.io//github/SEEK-Jobs/bx-backends).
WARN: Use matchDepNames instead of matchPackageNames
> fix: rename matchPackageNames to matchDepNames as per renovate warning

- default.json
We faced an issue in this renovate [PR](https://github.com/SEEK-Jobs/indie-graphql-op-sampler/pull/865) where the CI failed due to the `serverless` package version is not compatible with the `aws-sdk/*` packages
Suggesting to bundle them in into the same group to perform upgrade together.
We did an experiment of the renovate config in this [PR](https://github.com/SEEK-Jobs/indie-jepsen/pull/787) and it's looking good in https://github.com/SEEK-Jobs/indie-jepsen/pull/789
> Add serverless into aws-sdk group update

- default.json
I see a number of branches which just go stale and constantly trigger CI runs when they get force pushed by Renovate. I don't think that it's very useful given most of our repos require our branches to be updated before being merged into the default branch.
This change limits the number of branches to the same as the pr limit.
> Adjust branchConcurrentLimit

- default.json
> `null` (default) inherits value from `prConcurrentLimit`
https://docs.renovatebot.com/configuration-options/#branchconcurrentlimit
> Set `branchConcurrentLimit` to null

- default.json
- non-critical.json
- third-party-major.json
This is important for reproducible builds. 
It's a best practise per Renovate, and they have a good explanation here: https://docs.renovatebot.com/docker/#digest-pinning.
> Digest Pinning
> We recommend that you pin your Docker images to an exact digest. By pinning to a digest you make your Docker builds immutable, every time you do a pull you get the same content.
> 
> If you work with dependencies in the JavaScript/npm ecosystem, you may be used to exact versions being immutable. For example, if you set a version like 2.0.1, you and your colleagues always get the exact same "code".
> 
> Docker's tags are not immutable versions, even if tags look like a version. You probably expect myimage:1 and > myimage:1.2 to change over time, but you might incorrectly assume that myimage:1.2.0 never …
> Enable docker digest pinning

- default.json
- third-party-major.json
Raised by @juliuscheung. This might help with subsequent digest PRs refusing to be automerged.
> Try recreateWhen: always for digest pinning

- default.json
I don't know if this is necessary, feel free to close if not.
> Block new pnpm version with busted `fetch`

- default.json
Reminder to revert #134 ~~once we have an upstream fix.~~
I think the issue was in mismatched versions, so this was not necessary to block.
> Unblock pnpm upgrades

- default.json
- non-critical.json
I thought we always had this tbh, but for the same reason we exclude `@types/node`, it doesn't really make sense to bump .nvmrc in isolation. Skuba intends to release an autofix to get us more of the way there in one bang, later this year.
> Disable node majors

- default.json
- non-critical.json
- third-party-major.json
`sku` and the React ecosystem need to support & mature before we start rushing through upgrades
> Exclude react majors

- default.json
- non-critical.json
- third-party-major.json
Hopefully this helps with the obvious cases, though the dependency could still be pulled in transitively.
https://github.com/aws/aws-sdk-js-v3/issues/6816
> Block renovation to `@aws-sdk/credential-providers` 3.730.0

- default.json
- non-critical.json
- third-party-major.json
> Allow `@aws-sdk/credential-providers` >3.730.0

- .github/workflows/validate.yml
- default.json
- non-critical.json
- third-party-major.json
With Node LTS v22 and v20 now including Corepack `v0.31`, [this restriction](https://github.com/seek-oss/rynovate/pull/160) is no longer necessary.
> Revert "RFC: Disable renovation for pnpm >=9.15.5"

- default.json
- non-critical.json
- third-party-major.json
Issues appears to be fixed in 5.44.0: https://github.com/DataDog/dd-trace-js/issues/5394
Seems happy in one of my services that was previously affected.
> Allow dd-trace 5.44.x+

- default.json
- non-critical.json
- third-party-major.json
I'd like us to have some time to deal with e.g. seek-oss/koala first, before these come through. I'm not 100% sure koa 3 will break things, but hoping to let things settle first, anyway.
https://github.com/koajs/koa/releases/tag/v3.0.0
> Block koa majors

- package.json
- third-party-major.json
Renovate raised a PR to update to [this version](https://www.npmjs.com/package/@types/koa-bodyparser/v/5.0.2) which was published 7 years ago and doesn't seem to exist on the versions page 🤔
> Block @types/koa-bodyparser v5.0.2

- default.json
- non-critical.json
- third-party-major.json
Turns out there are two more [v5.0.0](https://www.npmjs.com/package/@types/koa-bodyparser/v/5.0.0) & [v5.0.1](https://www.npmjs.com/package/@types/koa-bodyparser/v/5.0.1)
Extending https://github.com/seek-oss/rynovate/pull/174 again...
> Block @types/koa-bodyparser v5.0.0 & v5.0.1

- internal-shared.json
Latest major spams stdout by default.
https://github.com/motdotla/dotenv/blob/v17.2.1/CHANGELOG.md#1721-2025-07-24
> Disable `dotenv` >=17

- internal-shared.json
@types/koa is now out, and the breaking change is relatively mild for koa 3. We should be good to go.
https://github.com/seek-oss/skuba/pull/1974
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/73346
https://github.com/seek-oss/koala/pull/312
> Unblock koa upgrades

- internal-shared.json
Last one didn't seem to work.
Seems to require https://docs.renovatebot.com/configuration-options/#separatemajorminor to work.
There's some consequences to using separateMajorMinor so I've limited it to specific versions of koa and seek-koala
Tested in: https://github.com/samchungy/renovate-experiments
> Try group Koa again

- default.json
The aim of https://github.com/seek-oss/rynovate/pull/199 was to group the upgrading of serverless together like [this](https://github.com/zbrydon/test-renovate/pull/10). 
For some reason we saw
- https://github.com/SEEK-Jobs/indie-fka-twigs-crew/pull/2326 update the `serverless.yml`
followed by
- https://github.com/SEEK-Jobs/indie-fka-twigs-crew/pull/2329 update the `package.json` 
Since the second PR was a `npm dev dependencies` I am excluding serverless from that group, but this is a complete guess. 
Mainly because I expected the `package.json` version to have been caught and updated via
https://github.com/seek-oss/rynovate/blob/d82fffcf9accdf71bf563a5ade9d8fd35b71c893/default.json#L101-L106
> Exclude `serverless` from `npm dev dependencies` group
